feat: add method get_royalty_fee
aresrpg/aresrpg-sdk pull request #1
Opened 2024-07-04 10:05 UTC by SohKey

2024-07-04 11:46 UTC, Sceat requested changes
Awesome thanks! please include a try catch block in case the rule doesn't exist for the requested type!

2024-07-04 12:17 UTC, SohKey commented
> Awesome thanks! please include a try catch block in case the rule doesn't exist for the requested type!

Done 👍

2024-07-05 14:31 UTC, Sceat commented on src/sui/read/get_royalty_fee.js
> +      return null
```suggestion
      console.error(error)
      return null
```

2024-07-05 14:31 UTC, Sceat approved these changes

2024-07-05 14:31 UTC, merged